version: '3.5'
services:
    php:
        build:
            context: docker/php
            dockerfile: php.dockerfile
        volumes:
            - "./:/var/www/html"
        networks:
            - ychanter

    nginx:
        build:
            context: docker/nginx
            dockerfile: nginx.dockerfile
        volumes:
            - "./web:/app"
        links:
            - php
        ports:
            - "${SERVICE_PORT}:80"
        expose:
            - 80
        networks:
            - ychanter

networks:
    ychanter:
        name: ychanter-network
        external: true
