version: '3.5'
services:
    php:
        build:
            context: docker/php
            dockerfile: php.prod.dockerfile
        volumes:
            - "./:/var/www/html"
        links:
            - db
        depends_on:
            - db
        networks:
            - ychanter
            - ychanter-hydra

    nginx:
        build:
            context: docker/nginx
            dockerfile: nginx.dockerfile
        volumes:
            - "./web:/app"
        links:
            - php
        depends_on:
            - php
        networks:
            - ychanter

    db:
        image: postgres:12.12
        environment:
            POSTGRES_PASSWORD: $DB_ROOT_PASSWORD
        volumes:
            - "database_psql_volume:/var/lib/postgresql/data"
            - "./docker/db:/docker-entrypoint-initdb.d"
        networks:
            - ychanter-hydra

volumes:
    database_psql_volume:

networks:
    ychanter:
        name: ychanter-network
        external: true
    ychanter-hydra:
        name: ychanter-hydra
        driver: bridge
